### ISSUE TITLE
未能找到引用组件和缺少此项目引用的nuget程序包

### ISSUE THREAD

**Issue by OrangeSAM** [gutrse3321/.netmvc-AppMyRPG#1]
![tim 20180320172348](https://user-images.githubusercontent.com/23071208/37646042-8267aaf6-2c63-11e8-9e28-a096501149af.png)

对于引用组件，我尝试过了删除后手动添加，但没有用。
对于nuget程序，尝试了还原程序包，也没有反应。

请问您知道该怎么解决吗？

**Comment by gutrse3321** [comment]
实在不好意思，现在才看见。看先生应该是没有在从事C#，我其实也忘的差不多了。

**Comment by OrangeSAM** [comment]
嗯嗯，是的。
不碍事，麻烦了。
