### ISSUE TITLE
您的数据库是什么样的呢？？可否告知呢

### ISSUE THREAD

**Issue by 1604010326** [gutrse3321/.netmvc-AppMyRPG#2]

**Comment by gutrse3321** [comment]
sqlserver，之前本地是直接用的localdb，可以看readme直接修改xml使用线上或者本地创建的库。

**Comment by 1604010326** [comment]
您的数据库表是怎样的呢，还是说我链接上我的本地sqlserver表就自动建立了？

**Comment by gutrse3321** [comment]
我想一下，我记得是database first的，我需要去看一下代码

**Comment by 1604010326** [comment]
麻烦您了

**Comment by gutrse3321** [comment]
在App_Data下有sqlserver的mdf文件，你可以将它附加到sqlserver中，就有对应的数据库和相关表了

**Comment by gutrse3321** [comment]
注意使用的.NET Framework 4.5和EntityFramework 6.0版本

**Comment by 1604010326** [comment]
好的，我只要把connectionString改成我的连接串就可以了是吧，谢谢您，低版本是不是运行会报错呢

**Comment by gutrse3321** [comment]
以防万一，毕竟挺久远了

**Comment by 1604010326** [comment]
嘻嘻，懂了，再次感谢~~

**Comment by gutrse3321** [comment]
我这边先关闭issue了，有问题再提。
