### ISSUE TITLE
请问分类下拉框处报错怎么处理啊求助

### ISSUE THREAD

**Issue by 1604010326** [gutrse3321/.netmvc-AppMyRPG#3]
public class HomeController : Controller
    {
        DB_MyRPGEntities db = new DB_MyRPGEntities();
        // 最新更新
        public ActionResult Index(string order,string selectString,string currentFilter,int? page)
        {
            //给分类下拉框赋值
//这里报错了，不知道怎么发图片所以截图没放上来
            var typeName = db.GameType.Where(m => m.OIID == 2).ToList();
            List<string> name = new List<string>();
            foreach (var item in typeName)
            {
                name.Add(item.TypeName);
            }
            ViewBag.OrderNum = name;

            //保持分类在分页时相同

**Comment by gutrse3321** [comment]
抱歉很久没有回复，最近没有打开邮箱，我需要一个c#的环境重新浏览下代码去了解情况，如果想持续关注项目的话，可以添加在联系方式吗？类似QQ、微信等

**Comment by gutrse3321** [comment]
QQ: 464189307
Wechat: kokokomachi
这是我的联系方式，最近转去做java了在熟悉项目，可能响应不及时
